import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  homeMain: {
    width: '100%', // Prend toute la largeur
    maxWidth: 300, // Limite la largeur
    height: '80%', // Prend 80% de la hauteur
    marginTop: 40,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: 0,
  },
  tabContent: {
    padding: 8,
    backgroundColor: '#001A31', // Bleu foncé
    color: '#fff', // Texte blanc
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    maxWidth: '100%',
    width: '100%',
    maxHeight: '100%',
    boxSizing: 'border-box',
    overflowY: 'scroll',
  },
  homeContainer: {
    backgroundColor: '#010E1E', // Fond général
    color: '#fff', // Texte blanc
    padding: 20,
    borderRadius: 8,
    maxWidth: 300,
    marginVertical: 1,
    height: '95%',
    position: 'relative',
    overflow: 'hidden',
    borderColor: '#001A31',
    borderWidth: 1,
    shadowColor: '#001A31',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  topSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 6,
    backgroundColor: '#001A31',
    marginBottom: 5,
    marginTop: 5,
    width: 300,
    height: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  selectedClubInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#001A31',
    padding: 10,
    marginBottom: 10,
  },
  selectedClubLogo: {
    width: 30,
    height: 30,
    borderRadius: 50,
    marginRight: 10,
    resizeMode: 'cover',
  },
  selectedClubName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  mainSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  inputContainer: {
    flexDirection: 'column',
    flex: 1,
    backgroundColor: '#001A31',
    position: 'relative',
  },
  inputSection: {
    flexDirection: 'column',
    backgroundColor: '#001A31',
    width: '100%',
    marginBottom: 10,
  },
  inputText: {
    width: '100%',
    paddingVertical: 5,
    paddingHorizontal: 20,
    fontSize: 16,
    borderColor: '#ddd',
    backgroundColor: '#001A31',
    color: '#fff',
    borderWidth: 0,
    boxSizing: 'border-box',
    transition: 'background-color 0.3s ease',
  },
  searchResults: {
    position: 'absolute',
    width: '100%',
    top: '100%',
    left: 0,
    backgroundColor: '#fff',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    cursor: 'pointer', // Ceci est un style spécifique au web, pas supporté par React Native
  },
  searchResultItemHovered: {
    backgroundColor: '#f0f0f0',
  },
  resultLogo: {
    width: 30,
    height: 30,
    borderRadius: 50,
    marginRight: 10,
    resizeMode: 'cover',
  },
  resultName: {
    fontSize: 16,
    color: '#333',
    flexShrink: 1, // Pour gérer le texte long
  },
  counterContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#001A31',
    padding: 5,
  },
  counterLabel: {
    fontSize: 20,
    marginVertical: 10,
    fontWeight: 'bold',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 2,
    width: '100%',
  },
  buttonPause: {
    width: 80,
    height: 80,
    borderWidth: 20,
    borderColor: '#fff',
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 40,
    backgroundColor: '#fff',
    color: 'red',
  },
  buttonAction: {
    width: 80,
    height: 80,
    borderRadius: 50,
    backgroundImage: 'url("action.PNG")', // Les images sont gérées différemment en React Native, utilise require() si c'est un fichier local
    backgroundSize: 'cover',
    transition: 'transform 0.3s ease',
  },
  timer: {
    fontSize: 16,
    marginTop: 20,
    color: '#555',
  },
  message: {
    fontSize: 14,
    marginTop: 20,
    padding: 10,
    backgroundColor: '#001A31',
    color: '#fff',
    borderLeftWidth: 4,
    borderLeftColor: '#007bff',
    borderRadius: 6,
    textAlign: 'center',
  },
});

export default styles;
