runtime: nodejs22
instance_class: F4_1G

# Variables d'environnement pour la configuration de la base de données
env_variables:
  DB_HOST: '34.163.248.199' # Adresse IP publique de votre instance Cloud SQL
  DB_USER: 'postgres' # Remplacez par le nom d'utilisateur de votre base de données
  DB_PASS: 'postgres' # Remplacez par le mot de passe de votre base de données
  DB_NAME: 'iasportvision2025' # Remplacez par le nom de la base de données
  DB_PORT: '5432' # Port par défaut de votre instance Cloud SQL
  
  ROLLING_AUTOTICK_ENABLED: "1"
  ROLLING_AUTOTICK_INTERVAL_SEC: "10"
  ROLLING_LOG_DOWNLOADURL_EVERY: "1"
  ROLLING_SPLIT_ON_TIMEOUT: "1"
  ROLLING_SPLIT_PART_SEC: "20"
  ROLLING_PARALLEL_SAVE: "1"
  ROLLING_PARALLEL_POLL: "1"
  ROLLING_PARALLEL_DOWNLOAD: "3"
  ROLLING_FINALIZE_PREFETCH: "3"
  CLOUD_TASKS_LOCATION: "europe-west6"
  CLOUD_TASKS_QUEUE: "hikconnect-rolling"
  ROLLING_AUTOTICK_SECRET: "9f3c7a8b1d4e6f2a9c0b5e7d3a1f8c6e2d9a4b7c1e6f3d8a0b2c5e9f7a4d1c3"
# Connexion à Cloud SQL (format : <PROJECT_ID>:<REGION>:<INSTANCE_NAME>)
beta_settings:
  cloud_sql_instances: 'ia-sport:europe-west9:ia-sport-vision'
