-- Migration 005 : tables d'enregistrement vidéo (Cloud SQL = source de vérité).
--
--   current_recording  : un match enregistré (1 ligne par session rolling).
--   recording_segments : segments générés par le rolling (1 ligne par chunk).
--   recording_log      : journal chronologique des événements d'un enregistrement.
--
-- Objectif : encadrer le moteur de rolling existant (état GCS conservé) avec une
-- base relationnelle traçable. L'écriture en base est faite en best-effort par
-- l'API (dual-write) : elle ne doit jamais bloquer le rolling.
--
-- Idempotent : CREATE ... IF NOT EXISTS partout. Réutilise set_updated_at()
-- (définie en migration 001).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────── current_recording ───────────────────────────
CREATE TABLE IF NOT EXISTS current_recording (
  id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Pont GCS <-> SQL : identifiant de la session rolling (state GCS).
  -- UNIQUE => un enregistrement correspond à une seule session rolling.
  rolling_id         TEXT         UNIQUE,

  -- Rattachement métier. club_id peut être NULL si la caméra n'est pas (encore)
  -- enregistrée dans la table devices (un WARNING est journalisé dans ce cas).
  club_id            UUID         REFERENCES clubs(id) ON DELETE SET NULL,
  device_id          TEXT,
  camera_id          TEXT,

  club_domicile      TEXT,
  club_adverse       TEXT,

  nom_video          TEXT,

  date_debut         TIMESTAMPTZ,
  date_fin           TIMESTAMPTZ,
  duration_seconds   INTEGER,

  status             TEXT         NOT NULL DEFAULT 'EN_COURS'
                       CHECK (status IN ('EN_COURS', 'COMPLET', 'TIMEOUT', 'ERREUR')),

  last_rolling_at    TIMESTAMPTZ,
  last_file_found_at TIMESTAMPTZ,
  last_file_name     TEXT,

  -- Vidéo finale (source de vérité).
  final_gcs_path     TEXT,
  final_public_url   TEXT,

  error_message      TEXT,

  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS current_recording_club_id_idx   ON current_recording (club_id);
CREATE INDEX IF NOT EXISTS current_recording_camera_id_idx ON current_recording (camera_id);
CREATE INDEX IF NOT EXISTS current_recording_status_idx    ON current_recording (status);
CREATE INDEX IF NOT EXISTS current_recording_created_at_idx ON current_recording (created_at);

-- Règle métier : une caméra ne peut avoir qu'un seul enregistrement EN_COURS.
CREATE UNIQUE INDEX IF NOT EXISTS current_recording_one_active_per_camera_idx
  ON current_recording (camera_id)
  WHERE status = 'EN_COURS';

DROP TRIGGER IF EXISTS current_recording_set_updated_at ON current_recording;
CREATE TRIGGER current_recording_set_updated_at
  BEFORE UPDATE ON current_recording
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── recording_segments ───────────────────────────
CREATE TABLE IF NOT EXISTS recording_segments (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

  recording_id   UUID         NOT NULL REFERENCES current_recording(id) ON DELETE CASCADE,

  club_id        UUID         REFERENCES clubs(id) ON DELETE SET NULL,
  camera_id      TEXT,

  segment_index  INTEGER      NOT NULL,

  file_name      TEXT,
  file_size      BIGINT,

  date_debut     TIMESTAMPTZ,
  date_fin       TIMESTAMPTZ,

  status         TEXT         NOT NULL DEFAULT 'OK'
                   CHECK (status IN ('OK', 'ERREUR')),

  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  -- Idempotence du dual-write : un segment = (enregistrement, index).
  UNIQUE (recording_id, segment_index)
);

CREATE INDEX IF NOT EXISTS recording_segments_recording_id_idx ON recording_segments (recording_id);
CREATE INDEX IF NOT EXISTS recording_segments_club_id_idx      ON recording_segments (club_id);

DROP TRIGGER IF EXISTS recording_segments_set_updated_at ON recording_segments;
CREATE TRIGGER recording_segments_set_updated_at
  BEFORE UPDATE ON recording_segments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── recording_log ───────────────────────────
-- Journal append-only : BIGINT identity pour un ordre chronologique stable et
-- compact (volume potentiellement élevé). Pas de trigger updated_at (immuable).
CREATE TABLE IF NOT EXISTS recording_log (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  recording_id  UUID         REFERENCES current_recording(id) ON DELETE CASCADE,

  club_id       UUID         REFERENCES clubs(id) ON DELETE SET NULL,
  camera_id     TEXT,

  level         TEXT         NOT NULL DEFAULT 'INFO'
                  CHECK (level IN ('INFO', 'WARNING', 'ERROR')),

  event_type    TEXT         NOT NULL,
  message       TEXT,
  details_json  JSONB,

  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS recording_log_recording_id_idx ON recording_log (recording_id, created_at);
CREATE INDEX IF NOT EXISTS recording_log_camera_id_idx    ON recording_log (camera_id, created_at);
CREATE INDEX IF NOT EXISTS recording_log_event_type_idx   ON recording_log (event_type);
